mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

mysite/polls/urls.py
from django.urls import path

from . import views


app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    
def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, default=1)

mysite/polls/views.py
from typing import Any, Dict
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.contrib.auth.decorators import login_required

from .models import Choice, Question, Vote


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"
    context_object_name = "question"
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        question = self.get_object()
        choices = question.choice_set.all()
        data = [{'choice_text': choice.choice_text, 'votes': choice.votes} for choice in choices]
        context['data'] = data
        context['question'] = question
        return context

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        user = request.user
        selected_choice.votes += 1
        selected_choice.save()
        vote = Vote.objects.create(user=user, choice=selected_choice)
        return HttpResponseRedirect(reverse("polls:results", args=(question_id,)))

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title%}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <ul class="nav nav-tabs">
        {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link active">User: {{ user.get_username }}</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li class="nav-item" ><a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
        {% endif %}
    </ul>
    <nav class="navbar navbar-expand-lg bd-body-tertiary bg-primary">
        <div class="container-fluid ">
            <a class="navbar-brand">Polls</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                  <a class="nav-link" href="{% url 'polls:index' %}" class="navbar-item">Questions</a>
                  {% block results %}{% endblock %}
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

mysite/polls/templates/polls/detail.html
{% extends "polls/base.html"%}
{% block title %}Vote Form{% endblock %}
{% block results%}<a class="nav-link" href="{% url 'polls:results' question.id %}" class="navbar-item">Results</a>{% endblock %}
{% block content %}
    <br><br>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
            <fieldset>
                <legend><h1>{{ question.question_text }}</h1></legend>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                <br>
                <ul class="list-group">
                    {% for choice in question.choice_set.all %}
                    <li class="list-group-item list-group-item-action">
                        <input class="form-check-input me-1" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                        <label class="form-check-label stretched-link" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                    </li>
                    {% endfor %}
                </ul>
                <br>
            </fieldset>
        <input type="submit" class="btn btn-primary" value="Vote">
    </form>
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends "polls/base.html"%}
{% block title %}Questions{% endblock %}
{% block content %}
<br>
    <h1>Questions</h1>
    <br>
    {% if latest_question_list %}
    <ul class="list-group">
        {% for question in latest_question_list %}
            <li class="list-group-item">
                <a class="btn btn-primary" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <span class="placeholder col-12 bg-danger"></span>
    <p>No polls are available.</p>
    <span class="placeholder col-12 bg-danger"></span>
    {% endif %}
{% endblock %} 

mysite/polls/templates/polls/results.html
{% extends "polls/base.html"%}
{% block title %}Results{% endblock %}
{% block content %}
<br>
<h1>{{ question.question_text }}</h1>
<br>
<h3>Chart</h3>
<div>
    <canvas id="myChart"></canvas>
</div>
  
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  
  <script>
    const ctx = document.getElementById('myChart');
  
    var labels = [
        {% for item in data %}
            '{{ item.choice_text }}',
        {% endfor %}
    ];

    var votes = [
        {% for item in data %}
            {{ item.votes }},
        {% endfor %}
    ];

    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: labels,
        datasets: [{
          label: '# of Votes',
          data: votes,
          borderWidth: 3
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  </script>
<br>
<h3>Voters</h3>
<table class="table table-light table-striped">
    <thead>
        <tr>
            <th scope="col">Choice</th>
            <th scope="col">Voters</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for choice in question.choice_set.all %}
        <tr>
            <td>{{ choice.choice_text }}</td>
            <td>
              <ul class="list-group list-group-flush">
                {% for vote in choice.vote_set.all %}
                  <li class="list-group-item"> {{ vote.user.username }}</li>
                {% endfor %}
              </ul>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div>
<a href="{% url 'polls:detail' question.id %}" class="btn btn-primary">Vote again?</a>
</div>
{% endblock %} 